/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.components;

import entidades.Usuario;
import entidades.permisos;
import entidades.tipoPermisos;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.JTextArea;
import logica.funcionesComunes;

/**
 *
 * @author programador1
 */
public class pnlInfoPermiso extends javax.swing.JPanel {

    /**
     * Creates new form pnlInfoPermiso
     */
    public pnlInfoPermiso() {
        initComponents();
        vista.util.botonComun.mouseHoverListener(this.btnEditar);
        vista.util.botonComun.mouseHoverListener(this.btnAprobarDirecto);
        vista.util.botonComun.mouseHoverListener(this.btnDelete);
        vista.util.botonComun.mouseHoverListener(this.btnVisto);
        vista.util.botonComun.mouseHoverListener(this.btnDenegar);
    }
    
    public void mostrarPermisoParaEditar(javax.swing.JList<String> jlistPermisosPendientes, Usuario usuarioPermiso, ArrayList<Usuario> subEmpleConPermsPend, ArrayList<permisos> subListaPerPend, permisos permisoActual, ArrayList<tipoPermisos> listaTipoPermisos, Icon iconComprobanteActual, JTextArea txtareaInformacion) {
        
        try {
            int index = jlistPermisosPendientes.getSelectedIndex();
            usuarioPermiso = subEmpleConPermsPend.get(index);
            permisoActual = subListaPerPend.get(index);
            
            String tipo = entidades.tipoPermisos.getDescriptionPermiso(listaTipoPermisos, permisoActual.getIdTipo_permiso());
            this.lbUsuarioInf.setText("Nombre: " + usuarioPermiso.getNombre() + " " + usuarioPermiso.getApellido1() + " " + usuarioPermiso.getApellido2());
            this.lbEstado.setText("Estado: " + permisos.getDescripcionEstado(permisoActual.getEstado()));
            //this.lbUsuarioInf.setText("");
            this.lbFechaSolicitud.setText("Solicitado: " + funcionesComunes.getCommunDates(permisoActual.getFecha_creacion()));
            this.lbFechas.setText("Desde " + funcionesComunes.getCommunDates(permisoActual.getFecha_inicio()) + ", hasta " + funcionesComunes.getCommunDates(permisoActual.getFecha_fin()));
            this.lbObservaciones.setText("Observaciones: " + permisoActual.getObserbaciones());
            this.lbTrabajar.setText("Trabajar " + permisos.getDescripcionTrabajar(permisoActual.getTrabajar()));
            this.lbComprobante.setText("Comprobante: " + permisoActual.getIdComprobante());
            this.lbTipoPermiso.setText("Tipo permiso: " + tipo);
            if (permisoActual.getIdComprobante() > 0) {
                iconComprobanteActual = logica.comprobanteLogica.getImagenComprobante(permisoActual.getIdComprobante());
            }
        } catch (Exception e) {
            System.out.println("vista.mantenimiento02.mostrarPermisoParaEditar()");
            System.out.println("error: " + e.getMessage());
            txtareaInformacion.setText("");
        }
        
    }
    
    public void clearForm() {
        this.lbUsuarioInf.setText("");
        this.lbEstado.setText("");
        this.lbFechaSolicitud.setText("");
        this.lbFechas.setText("");
        this.lbObservaciones.setText("");
        this.lbTrabajar.setText("");
        this.lbComprobante.setText("");
        this.lbTipoPermiso.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        center = new javax.swing.JPanel();
        lbUsuarioInf = new javax.swing.JLabel();
        lbTipoPermiso = new javax.swing.JLabel();
        lbFechaSolicitud = new javax.swing.JLabel();
        lbFechas = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        lbObservaciones = new javax.swing.JLabel();
        lbComprobante = new javax.swing.JLabel();
        lbTrabajar = new javax.swing.JLabel();
        top = new javax.swing.JPanel();
        down = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnVisto = new javax.swing.JButton();
        btnAprobarDirecto = new javax.swing.JButton();
        btnDenegar = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        rigth = new javax.swing.JPanel();
        left = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true), "SOLICITUD ACTUAL"));
        setLayout(new java.awt.BorderLayout());

        center.setBackground(new java.awt.Color(255, 255, 255));
        center.setLayout(new java.awt.GridLayout(8, 1, 5, 5));
        center.add(lbUsuarioInf);
        center.add(lbTipoPermiso);
        center.add(lbFechaSolicitud);
        center.add(lbFechas);
        center.add(lbEstado);
        center.add(lbObservaciones);
        center.add(lbComprobante);
        center.add(lbTrabajar);

        add(center, java.awt.BorderLayout.CENTER);

        top.setBackground(new java.awt.Color(255, 255, 255));
        top.setPreferredSize(new java.awt.Dimension(400, 20));

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        add(top, java.awt.BorderLayout.PAGE_START);

        down.setBackground(new java.awt.Color(255, 255, 255));
        down.setPreferredSize(new java.awt.Dimension(400, 50));

        btnEditar.setToolTipText("Click para editar la solicitud");
        btnEditar.setBackground(new java.awt.Color(204, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-edit-30.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        down.add(btnEditar);

        btnVisto.setToolTipText("Dejar solicitud como vista");
        btnVisto.setBackground(new java.awt.Color(204, 255, 255));
        btnVisto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-double-tick-30.png"))); // NOI18N
        btnVisto.setText("VISTO");
        down.add(btnVisto);

        btnAprobarDirecto.setToolTipText("Click para dejar en visto");
        btnAprobarDirecto.setBackground(new java.awt.Color(204, 255, 255));
        btnAprobarDirecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-facebook-like-30.png"))); // NOI18N
        btnAprobarDirecto.setText("APROBAR");
        down.add(btnAprobarDirecto);

        btnDenegar.setToolTipText("Denegar solicitud");
        btnDenegar.setBackground(new java.awt.Color(204, 255, 255));
        btnDenegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-thumbs-down-30.png"))); // NOI18N
        btnDenegar.setText("DENEGAR");
        down.add(btnDenegar);

        btnDelete.setToolTipText("Eliminar solicitud");
        btnDelete.setBackground(new java.awt.Color(204, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-remove-30.png"))); // NOI18N
        btnDelete.setText("ELIMINAR");
        down.add(btnDelete);

        add(down, java.awt.BorderLayout.PAGE_END);

        rigth.setBackground(new java.awt.Color(255, 255, 255));
        rigth.setMaximumSize(new java.awt.Dimension(20, 300));
        rigth.setMinimumSize(new java.awt.Dimension(20, 300));
        rigth.setPreferredSize(new java.awt.Dimension(20, 300));

        javax.swing.GroupLayout rigthLayout = new javax.swing.GroupLayout(rigth);
        rigth.setLayout(rigthLayout);
        rigthLayout.setHorizontalGroup(
            rigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        rigthLayout.setVerticalGroup(
            rigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(rigth, java.awt.BorderLayout.LINE_END);

        left.setBackground(new java.awt.Color(255, 255, 255));
        left.setMaximumSize(new java.awt.Dimension(20, 300));
        left.setMinimumSize(new java.awt.Dimension(20, 300));
        left.setPreferredSize(new java.awt.Dimension(20, 300));

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(left, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAprobarDirecto;
    public javax.swing.JButton btnDelete;
    public javax.swing.JButton btnDenegar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnVisto;
    private javax.swing.JPanel center;
    private javax.swing.JPanel down;
    public javax.swing.JLabel lbComprobante;
    public javax.swing.JLabel lbEstado;
    public javax.swing.JLabel lbFechaSolicitud;
    public javax.swing.JLabel lbFechas;
    public javax.swing.JLabel lbObservaciones;
    public javax.swing.JLabel lbTipoPermiso;
    public javax.swing.JLabel lbTrabajar;
    public javax.swing.JLabel lbUsuarioInf;
    private javax.swing.JPanel left;
    private javax.swing.JPanel rigth;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
