/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import entidades.Usuario;
import entidades.departamento;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.ImageIcon;
import logica.funcionesComunes;
import logica.repostory;

/**
 *
 * @author programador1
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    boolean dbChecked;
    Runnable usuariosThread;

    public login() {
        initComponents();
        this.btnLoading.setVisible(false);
        ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/images/icons8-traveler-30.png"));
        setIconImage(icon.getImage());
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        funcionesComunes.justNumbers(this.txtCodigoEmpleado, 4);
        File file = new File("./src/comprobantes/");
        funcionesComunes.deleteFiles(file);
        this.dbChecked = false;
        checkDb();
        clearImagesComprobantesDirectory();
        checkDirectories();
        this.usuariosThread = new Runnable() {
            @Override
            public void run() {
                btnLoading.setVisible(true);
                logIn();
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoEmpleado = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        lbInfor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnLoading = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel6.add(jLabel2);

        jPanel1.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel7.setLayout(new java.awt.GridLayout(4, 1, 10, 10));

        jLabel1.setText("INGRESE SU ID POR FAVOR");
        jPanel7.add(jLabel1);

        txtCodigoEmpleado.setText("jPasswordField1");
        txtCodigoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoEmpleadoActionPerformed(evt);
            }
        });
        txtCodigoEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoEmpleadoKeyPressed(evt);
            }
        });
        jPanel7.add(txtCodigoEmpleado);

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-login-rounded-30.png"))); // NOI18N
        btnIngresar.setText("INGRESAR");
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel7.add(btnIngresar);

        lbInfor.setBackground(new java.awt.Color(255, 255, 255));
        lbInfor.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lbInfor.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.add(lbInfor);

        jPanel1.add(jPanel7);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(432, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(432, 40));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnLoading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-dots-loading.gif"))); // NOI18N
        btnLoading.setBorderPainted(false);
        btnLoading.setContentAreaFilled(false);
        jPanel3.add(btnLoading);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(20, 197));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(20, 197));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoEmpleadoActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        if (this.dbChecked) {
            //logIn();
            Thread t = new Thread(usuariosThread);
            t.start();
        }


    }//GEN-LAST:event_btnIngresarActionPerformed
    /**
     * this function checks if the database exists if the database do not exists
     * its created
     *
     */
    private void checkDb() {
        String db = "gestion_vacaciones_permisos";
        boolean flag = logica.dbSettings.checkbGestionVacaciones(db);
        if (flag) {
            System.out.println("database checked");
            this.dbChecked = true;
        } else {
            boolean dbGestionCreada = logica.dbSettings.createDbGestionVacaciones();
            if (dbGestionCreada) {
                this.dbChecked = logica.dbSettings.createDbstructure();
            }
        }

    }

    /**
     * this function checks if the directory images exists if it do not, the it
     * is created
     */
    private void checkDirectories() {
        String fileName = repostory.getImagesPath();
        String comprobantesPath = repostory.getComprobantesPath();
        if (!funcionesComunes.checkDirectory(fileName)) {
            funcionesComunes.createDirectory(fileName);
        }
        if (!funcionesComunes.checkDirectory(comprobantesPath)) {
            funcionesComunes.createDirectory(comprobantesPath);
        }
    }

    /**
     * this function checks if the directory images comprobantes exists if it do
     * not, the it is created
     */
    private void clearImagesComprobantesDirectory() {
        String path = repostory.getComprobantesPath();
        boolean res = funcionesComunes.clearDirectry(path);
        if (res) {
            System.out.println("comprobantes deleted");
        }
    }

    private void logIn() {
        this.lbInfor.setText("");
        int id = 0;
        try {
            System.out.println("id " + this.txtCodigoEmpleado.getText());
            id = Integer.parseInt(this.txtCodigoEmpleado.getText());

        } catch (Exception e) {
            id = 0;
            btnLoading.setVisible(false);
            System.out.println(e.getMessage());

        }
        if (id == 0) {
            this.lbInfor.setText("Ingrese su id por favor");
        } else {

            Usuario us = logica.UsuarioLogica.getUsuario(id);
            //this.jPanel3.setVisible(false);
            if (us != null) {
                mantenimientoVacaciones mntv = new mantenimientoVacaciones(us);
                mntv.setVisible(true);
                this.dispose();
            } else {
                this.lbInfor.setText("Usuario incorrecto");
                btnLoading.setVisible(false);
            }
        }
        //btnLoading.setVisible(false);
    }
    private void txtCodigoEmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoEmpleadoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //logIn();
            Thread t = new Thread(usuariosThread);
            t.start();
        }
    }//GEN-LAST:event_txtCodigoEmpleadoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLoading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbInfor;
    private javax.swing.JPasswordField txtCodigoEmpleado;
    // End of variables declaration//GEN-END:variables
}
